export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
